sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo # build master branch only
before_install:
- npm install hexo-cli -g #安装Hexo脚手架工具
- npm audit fix
install:
- npm install  #安装package.json中的依赖
script:
- hexo clean
- hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: public
  target_branch: master
notifications:
email:
  - sanyuedev@gmail.com
on_success: always
on_failure: always
  