sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo # build master branch only
install:
  - npm install
script:
  - npm audit fix --force # 执行修复命令
after_script:
  - hexo clean
  - hexo g # generate static files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexo
  local-dir: public
  target_branch: master
